---
name: "Release collection on Automation Hub"
on:
  release:
    types: [published]

jobs:
  release_automation_hub:
    uses: ansible/ansible-content-actions/.github/workflows/release_ah.yaml@main
    with:
      environment: release
    secrets:
      ah_client_id: ${{ secrets.AH_CLIENT_ID }}
      ah_client_secret: ${{ secrets.AH_CLIENT_SECRET }}
